openapi: 3.0.0
info:
  title: cogit
  version: '1.0'
  contact:
    name: Penthai & Olivier
  description: Passerelle d'échange entre l'IHM et les autres outils (Bitbucket & Jira)
servers:
  - url: 'http://localhost:3000'
tags:
  - name: cogit
paths:
  /briques:
    get:
      summary: Liste des briques
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                title: brique
                type: array
                x-examples:
                  cokpit:
                    projectKey: cokpit
                    repoName: cokpit
                    repoSlug: cokpit
                  portik:
                    projectKey: TEAM_PFD
                    repoName: portik
                    repoSlug: portik
                  amir:
                    projectKey: AMIR
                    repoName: amir
                    repoSlug: amir
                description: Brique au sens cogit
                items:
                  $ref: '#/components/schemas/Brique'
              examples:
                briques:
                  value:
                    - project: COKPIT
                      repository: cokpit
                    - project: AMIR
                      repository: amir
                    - project: TEAM_PFD
                      repository: portik
                    - project: FORMATION
                      repository: formation
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                Error 400:
                  value:
                    errorStatus: 400
                    errorMessage: Bad Request
        '503':
          description: Service Unavailable
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                Error 503:
                  value:
                    errorStatus: 503
                    errorMessage: Service Unavailable
      operationId: get-briques
      description: |-
        Liste toutes les briques de Bitbucket (repos)

        This resource is anonymously accessible.

        **Note on permissions.** In absence of the {@code permission} query parameter the implicit 'read' permission is assumed. Please note that this permission is lower than the REPO_READ permission rather than being equal to it. The implicit 'read' permission for a given repository is assigned to any user that has any of the higher permissions, such as REPO_READ, as well as to anonymous users if the repository is marked as public. The important implication of the above is that an anonymous request to this resource with a permission level REPO_READ is guaranteed to receive an empty list of repositories as a result. For anonymous requests it is therefore recommended to not specify the permission parameter at all.
      parameters:
        - schema:
            type: string
            enum:
              - REPO_READ
              - REPO_WRITE
              - REPO_ADMIN
          in: query
          name: permission
          description: Droits sur les repos
          allowEmptyValue: true
    parameters: []
  '/projects/{projectKey}/repos/{repoSlug}/versions':
    get:
      summary: Liste les versions d'une brique (repo)
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ParentVersion'
              examples:
                versions:
                  value:
                    - name: '1.37'
                      versions:
                        - name: 1.37.2
                          createdDate: 565641545
                          lifeCycle: Livrée
                          currentCycle: null
                          description: bllk
                        - name: 1.37.1
                          createdDate: 565641545
                          lifeCycle: Livrée
                          currentCycle: null
                          description: bllk
                        - name: 1.37.0
                          createdDate: 565641545
                          lifeCycle: Livrée
                          currentCycle: null
                          description: bllk
                        - name: 1.37.0-rc1
                          createdDate: 565641545
                          lifeCycle: Release Candidate
                          currentCycle: rc1
                          description: bllk
                    - name: '1.36'
                      versions:
                        - name: 1.36.0
                          createdDate: 565641545
                          lifeCycle: Livrée
                          currentCycle: null
                          description: bllk
                        - name: 1.36.0-rc1
                          createdDate: 565641545
                          lifeCycle: Release Candidate
                          currentCycle: rc1
                          description: bllk
                    - name: '1.35'
                      versions:
                        - name: 1.35.2
                          createdDate: 565641545
                          lifeCycle: Livrée
                          currentCycle: null
                          description: bllk
                        - name: 1.35.1
                          createdDate: 565641545
                          lifeCycle: Livrée
                          currentCycle: null
                          description: bllk
                        - name: 1.35.0
                          createdDate: 565641545
                          lifeCycle: Livrée
                          currentCycle: null
                          description: bllk
                        - name: 1.35.0-a1
                          createdDate: 565641545
                          lifeCycle: Alpha
                          currentCycle: a1
                          description: bllk
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                Error 404:
                  value:
                    errorStatus: 404
                    errorMessage: Not Found
        '503':
          description: Service Unavailable
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                Error 503:
                  value:
                    errorStatus: 503
                    errorMessage: Service Unavailable
      operationId: get-versions
      description: Recherche les versions "parent (Release)" + toutes les versions associées d'un repository
    parameters:
      - schema:
          type: string
        name: projectKey
        in: path
        description: Clé du projet
        required: true
      - schema:
          type: string
        name: repoSlug
        in: path
        description: Slug du repo ("Friendly name")
        required: true
  '/projects/{projectKey}/repos/{repoSlug}/branches':
    parameters:
      - schema:
          type: string
        name: projectKey
        in: path
        required: true
        description: Clé du projet
      - schema:
          type: string
        name: repoSlug
        in: path
        required: true
        description: Slug du repo ("Friendly name")
    get:
      summary: Liste les branches d'une brique (repo)
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Branch'
              examples:
                branches:
                  value:
                    - id: refs/heads/develop
                      displayId: develop
                    - id: refs/heads/feature/dev
                      displayId: feature/dev
                    - id: refs/heads/master
                      displayId: master
                    - id: refs/heads/feature/COK-599-montee-de-version-du-socle
                      displayId: feature/COK-599-montee-de-version-du-socle
                    - id: refs/heads/feature/dev1
                      displayId: feature/dev1
                    - id: refs/heads/feature/COK-600-point-sur-les-vbds
                      displayId: feature/COK-600-point-sur-les-vbds
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                Error 404:
                  value:
                    errorStatus: 404
                    errorMessage: Not Found
        '503':
          description: Service Unavailable
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                Error 503:
                  value:
                    errorStatus: 503
                    errorMessage: Service Unavailable
      operationId: get-projectKey-repoSlug-branches
      description: Liste les branches d'une brique (repo)
  '/projects/{projectKey}/repos/{repoSlug}/pull-requests':
    get:
      summary: Liste les Pull-Requests
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PullRequest'
              examples:
                pull-requests:
                  value:
                    - id: 54
                      title: Feature/OTA-554
                      description: ''
                      state: OPEN
                      createdDate: 1583229634033
                      fromRef: feature/OTA-554
                      toRef: develop
                    - id: 29
                      title: test
                      description: ''
                      state: OPEN
                      createdDate: 1567007057310
                      fromRef: feature/test-create-task
                      toRef: master
                    - id: 13
                      title: feature-1
                      description: ''
                      state: OPEN
                      createdDate: 1587730341584
                      fromRef: feature/feature-1
                      toRef: develop
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                Error 401:
                  value:
                    errorStatus: 401
                    errorMessage: Unauthorized
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                Error 404:
                  value:
                    errorStatus: 404
                    errorMessage: Not Found
        '503':
          description: Service Unavailable
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                Error 503:
                  value:
                    errorStatus: 503
                    errorMessage: Service Unavailable
      operationId: get-pull-requests
      description: |-
        Liste toutes les pull-requests d'un repository.
        Il est nécessaire d'être authentifié pour accéder à cette ressource.
      security:
        - Basic Auth: []
    parameters:
      - schema:
          type: string
        name: projectKey
        in: path
        required: true
        description: Clé du projet
      - schema:
          type: string
        name: repoSlug
        in: path
        required: true
        description: Slug du repo ("Friendly name")
  '/projects/{projectName}/issues':
    get:
      summary: Liste de tickets Jira pour un projet
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Issue'
              examples:
                Liste de tickets:
                  value:
                    - id: 160769
                      key: PFDRC-3799
                      fields:
                        created: '2020-05-14T16:43:14.000+0200'
                        summary: '[Artifactory][Upgrade] Tests fonctionnels Homol Mise à jour produit'
                        priority:
                          iconUrl: 'https://jira-h.retraite.aa/images/icons/priorities/critical.svg'
                          name: 1 - Critique
                        issuetype:
                          iconUrl: 'https://jira-h.retraite.aa/secure/viewavatar?size=xsmall&avatarId=12815&avatarType=issuetype'
                          name: Récit
                        status:
                          iconUrl: 'https://jira-h.retraite.aa/images/icons/statuses/generic.png'
                          name: Ouvert
                        assignee: null
                    - id: 160767
                      key: PFDRC-3798
                      fields:
                        created: '2020-05-14T16:40:14.000+0200'
                        summary: '[Artifactory][Upgrade] Upgrade produit Homol '
                        priority:
                          iconUrl: 'https://jira-h.retraite.aa/images/icons/priorities/critical.svg'
                          name: 1 - Critique
                        issuetype:
                          iconUrl: 'https://jira-h.retraite.aa/secure/viewavatar?size=xsmall&avatarId=12815&avatarType=issuetype'
                          name: Récit
                        status:
                          iconUrl: 'https://jira-h.retraite.aa/images/icons/statuses/generic.png'
                          name: Terminée
                        assignee:
                          name: U09E322
                          emailAddress: oajour-ext@agirc-arrco.fr
                          displayName: OLIVIER AJOUR - EXTERNE
                          avatarUrls:
                            16x16: 'https://jira-h.retraite.aa/secure/useravatar?size=xsmall&ownerId=u09e322&avatarId=24001'
                            24x24: 'https://jira-h.retraite.aa/secure/useravatar?size=small&ownerId=u09e322&avatarId=24001'
                            32x32: 'https://jira-h.retraite.aa/secure/useravatar?size=medium&ownerId=u09e322&avatarId=24001'
                            48x48: 'https://jira-h.retraite.aa/secure/useravatar?ownerId=u09e322&avatarId=24001'
                    - id: 160766
                      key: PFDRC-3797
                      fields:
                        created: '2020-05-14T16:38:08.000+0200'
                        summary: '[Artifactory][Upgrade] Reprise des données Homol (GEDI) + côté serveur également'
                        priority:
                          iconUrl: 'https://jira-h.retraite.aa/images/icons/priorities/critical.svg'
                          name: 1 - Critique
                        issuetype:
                          iconUrl: 'https://jira-h.retraite.aa/secure/viewavatar?size=xsmall&avatarId=12815&avatarType=issuetype'
                          name: Récit
                        status:
                          iconUrl: 'https://jira-h.retraite.aa/images/icons/statuses/generic.png'
                          name: Terminée
                        assignee:
                          name: U09E322
                          emailAddress: oajour-ext@agirc-arrco.fr
                          displayName: OLIVIER AJOUR - EXTERNE
                          avatarUrls:
                            16x16: 'https://jira-h.retraite.aa/secure/useravatar?size=xsmall&ownerId=u09e322&avatarId=24001'
                            24x24: 'https://jira-h.retraite.aa/secure/useravatar?size=small&ownerId=u09e322&avatarId=24001'
                            32x32: 'https://jira-h.retraite.aa/secure/useravatar?size=medium&ownerId=u09e322&avatarId=24001'
                            48x48: 'https://jira-h.retraite.aa/secure/useravatar?ownerId=u09e322&avatarId=24001'
                    - id: 160764
                      key: PFDRC-3796
                      fields:
                        created: '2020-05-14T16:37:14.000+0200'
                        summary: '[Artifactory][Upgrade] Mise à jour produit sur assemblage'
                        priority:
                          iconUrl: 'https://jira-h.retraite.aa/images/icons/priorities/critical.svg'
                          name: 1 - Critique
                        issuetype:
                          iconUrl: 'https://jira-h.retraite.aa/secure/viewavatar?size=xsmall&avatarId=12815&avatarType=issuetype'
                          name: Récit
                        status:
                          iconUrl: 'https://jira-h.retraite.aa/images/icons/statuses/generic.png'
                          name: Terminée
                        assignee:
                          name: U09E322
                          emailAddress: oajour-ext@agirc-arrco.fr
                          displayName: OLIVIER AJOUR - EXTERNE
                          avatarUrls:
                            16x16: 'https://jira-h.retraite.aa/secure/useravatar?size=xsmall&ownerId=u09e322&avatarId=24001'
                            24x24: 'https://jira-h.retraite.aa/secure/useravatar?size=small&ownerId=u09e322&avatarId=24001'
                            32x32: 'https://jira-h.retraite.aa/secure/useravatar?size=medium&ownerId=u09e322&avatarId=24001'
                            48x48: 'https://jira-h.retraite.aa/secure/useravatar?ownerId=u09e322&avatarId=24001'
                    - id: 160760
                      key: PFDRC-3795
                      fields:
                        created: '2020-05-14T16:30:57.000+0200'
                        summary: '[Confluence][RH7] Mise à jour production (GEDI + CAB)'
                        priority:
                          iconUrl: 'https://jira-h.retraite.aa/images/icons/priorities/critical.svg'
                          name: 1 - Critique
                        issuetype:
                          iconUrl: 'https://jira-h.retraite.aa/secure/viewavatar?size=xsmall&avatarId=12815&avatarType=issuetype'
                          name: Récit
                        status:
                          iconUrl: 'https://jira-h.retraite.aa/images/icons/statuses/generic.png'
                          name: Ouvert
                        assignee: null
                    - id: 160758
                      key: PFDRC-3794
                      fields:
                        created: '2020-05-14T16:29:21.000+0200'
                        summary: '[Confluence][RH7] Tests fonctionnels sur l''homologation'
                        priority:
                          iconUrl: 'https://jira-h.retraite.aa/images/icons/priorities/critical.svg'
                          name: 1 - Critique
                        issuetype:
                          iconUrl: 'https://jira-h.retraite.aa/secure/viewavatar?size=xsmall&avatarId=12815&avatarType=issuetype'
                          name: Récit
                        status:
                          iconUrl: 'https://jira-h.retraite.aa/images/icons/statuses/generic.png'
                          name: Ouvert
                        assignee: null
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                Error OK:
                  value:
                    errorStatus: 404
                    errorMessage: Not Found
        '503':
          description: Service Unavailable
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                Error 503:
                  value:
                    errorStatus: 503
                    errorMessage: Service Unavailable
      operationId: get-tickets
      description: Liste de tickets Jira
    parameters:
      - schema:
          type: string
        name: projectName
        in: path
        required: true
components:
  schemas:
    Brique:
      title: Brique
      type: object
      x-examples:
        cokpit:
          project: COKPIT
          repository: cokpit
        portik:
          project: TEAM_PFD
          repository: portik
        amir:
          project: AMIR
          repository: amir
      description: Brique au sens cogit
      properties:
        project:
          type: string
          description: Clé du projet dans BitBucket
        repository:
          type: string
          description: Clé du repo dans Bitbucket
    ParentVersion:
      title: ParentVersion
      type: object
      x-examples:
        '1.37':
          name: '1.37'
          versions:
            - name: 1.37.2
              createdDate: 565641545
              lifeCycle: null
              currentCycle: null
              description: bllk
            - name: 1.37.1
              createdDate: 565641545
              lifeCycle: null
              currentCycle: null
              description: bllk
            - name: 1.37.0
              createdDate: 565641545
              lifeCycle: null
              currentCycle: null
              description: bllk
            - name: 1.37.0-rc1
              createdDate: 565641545
              lifeCycle: rc
              currentCycle: '1'
              description: bllk
      description: |-
        Modèle d'une version X.Y
        + Toutes ses versions 
           - X.Y.Z-aNN 
           - X.Y.Z-rcNN 
           - X.Y.Z
      properties:
        name:
          type: string
          description: Nom au format X.Y
        versions:
          type: array
          description: Liste de toutes les versions associées à la X.Y
          items:
            $ref: '#/components/schemas/Version'
    Version:
      title: Version
      type: object
      description: Détail d'une version
      x-examples:
        Version Alpha:
          name: 1.37.0-a1
          createdDate: 1567007057310
          lifeCycle: Alpha
          currentCycle: a1
          description: Lalalala description 1
        Version RC:
          name: 1.37.0-rc3
          createdDate: 1567007057310
          lifeCycle: Release Candidate
          currentCycle: rc3
          description: Lalalala description 2
        Livrée:
          name: 1.37.0
          createdDate: 1567007057310
          lifeCycle: Livrée
          currentCycle: ''
          description: Lalalala description 3
      properties:
        name:
          type: string
        createdDate:
          type: integer
          description: Date à laquelle a été posé le TAG dans GIT
          format: int64
        lifeCycle:
          type: string
        currentCycle:
          type: string
        description:
          type: string
    Branch:
      title: Branch
      type: object
      x-examples:
        Develop:
          id: refs/heads/develop
          displayId: develop
        Master:
          id: refs/heads/master
          displayId: master
        Feature Cokpit:
          id: refs/heads/feature/COK-593-mise-en-oeuvre-abandon-de-version
          displayId: feature/COK-593-mise-en-oeuvre-abandon-de-version
      description: Représentation d'une branche
      properties:
        id:
          type: string
          description: ID Bitbuket de la branche
        displayId:
          type: string
          description: Nom d'affichage
    PullRequest:
      title: PullRequest
      type: object
      description: Modèle de la Pull-Request
      x-examples:
        Pull-request Cokpit:
          id: 41
          title: Feature/COK-540 new artifactory filtrage et mise a jour des pom
          description: |-
            * COK-540: [New Artifactory] Filtrage et mise à jour des pom

                Task-Url: https://jira.retraite.aa/browse/COK-540

            J'ai supprimé l'antérieur car j'ai changé ce que j'avait fait. 
            Merci pour vos commentaires, c'est plus simple maintenant.
          state: OPEN
          createdDate: 1567007057310
          fromRef: feature/COK-540-new-artifactory-filtrage-et-mise-a-jour-des-pom
          toRef: develop
        Pull-request Demo_git:
          id: 11
          title: Release/1.1
          description: "* add a common feature\r\n* add an amaury feature\r\n* WEB-5196"
          state: OPEN
          createdDate: 1567007057310
          fromRef: release/1.1
          toRef: master
      properties:
        id:
          type: integer
          description: ID de la pull-request
        title:
          type: string
          description: Titre de la pull-request
        description:
          type: string
          description: description de la pull-resquest
        state:
          type: string
          description: etat de la pull-request
        createdDate:
          type: integer
          description: date de creation
          format: int64
        fromRef:
          type: string
          description: d'où provient la pull-request
        toRef:
          type: string
          description: vers où va la pull-request
    Issue:
      title: Issue
      type: object
      description: Modèle d'une issue (Ticket) dans Jira
      x-examples:
        Ticket sans responsable:
          id: 159717
          key: PFDRC-3761
          fields:
            created: '2020-05-07T10:10:19.000+0200'
            summary: MEP Ménage Artifactory
            priority:
              iconUrl: 'https://jira-h.retraite.aa/images/icons/priorities/critical.svg'
              name: 1 - Critique
            issuetype:
              iconUrl: 'https://jira-h.retraite.aa/secure/viewavatar?size=xsmall&avatarId=12815&avatarType=issuetype'
              name: Récit
            status:
              iconUrl: 'https://jira-h.retraite.aa/images/icons/statuses/generic.png'
              name: Prête
            assignee: null
        Ticket avec responsable:
          id: 163080
          key: PFDRC-3859
          fields:
            created: '2020-05-29T16:47:17.000+0200'
            summary: '[Alfresco][Upgrade] Reprise des données Homol (GEDI) + côté serveur également'
            priority:
              iconUrl: 'https://jira-h.retraite.aa/images/icons/priorities/critical.svg'
              name: 1 - Critique
            issuetype:
              iconUrl: 'https://jira-h.retraite.aa/secure/viewavatar?size=xsmall&avatarId=12815&avatarType=issuetype'
              name: Récit
            status:
              iconUrl: 'https://jira-h.retraite.aa/images/icons/statuses/generic.png'
              name: Terminée
            assignee:
              name: U09E322
              emailAddress: oajour-ext@agirc-arrco.fr
              displayName: OLIVIER AJOUR - EXTERNE
              avatarUrls:
                16x16: 'https://jira-h.retraite.aa/secure/useravatar?size=xsmall&ownerId=u09e322&avatarId=24001'
                24x24: 'https://jira-h.retraite.aa/secure/useravatar?size=small&ownerId=u09e322&avatarId=24001'
                32x32: 'https://jira-h.retraite.aa/secure/useravatar?size=medium&ownerId=u09e322&avatarId=24001'
                48x48: 'https://jira-h.retraite.aa/secure/useravatar?ownerId=u09e322&avatarId=24001'
      properties:
        id:
          type: integer
        key:
          type: string
        fields:
          type: object
          properties:
            created:
              type: string
            summary:
              type: string
            priority:
              $ref: '#/components/schemas/Priority'
            issuetype:
              $ref: '#/components/schemas/Type'
            status:
              $ref: '#/components/schemas/Status'
            assignee:
              $ref: '#/components/schemas/User'
    Error:
      title: Error
      type: object
      properties:
        errorStatus:
          type: integer
        errorMessage:
          type: string
      description: Modèle des codes d'erreurs
      x-examples:
        Error 400:
          errorStatus: 400
          errorMessage: Bad request
        Error 503:
          errorStatus: 503
          errorMessage: Service unavailable
        Error 401:
          errorStatus: 401
          errorMessage: Unauthorized
        Error 404:
          errorStatus: 404
          errorMessage: Not Found
    Priority:
      title: Priority
      type: object
      properties:
        iconUrl:
          type: string
        name:
          type: string
      description: Priorité d'un ticket dans Jira
      x-examples:
        Mineure:
          iconUrl: 'https://jira-h.retraite.aa/images/icons/priorities/minor.svg'
          name: 3 - Mineure
        Critique:
          iconUrl: 'https://jira-h.retraite.aa/images/icons/priorities/critical.svg'
          name: 1 - Critique
    Type:
      title: Type
      type: object
      properties:
        iconUrl:
          type: string
        name:
          type: string
      description: Type d'un ticket dans Jira
      x-examples:
        Récit:
          iconUrl: 'https://jira-h.retraite.aa/secure/viewavatar?size=xsmall&avatarId=12815&avatarType=issuetype'
          name: Récit
        Anomalie:
          iconUrl: 'https://jira-h.retraite.aa/secure/viewavatar?size=xsmall&avatarId=12803&avatarType=issuetype'
          name: Anomalie
    Status:
      title: Status
      type: object
      properties:
        iconUrl:
          type: string
        name:
          type: string
      description: Statut (état) d'un ticket Jira
      x-examples:
        Terminée:
          iconUrl: 'https://jira-h.retraite.aa/images/icons/statuses/generic.png'
          name: Terminée
        En cours de développement:
          iconUrl: 'https://jira-h.retraite.aa/images/icons/statuses/generic.png'
          name: En cours de développement
    User:
      title: User
      type: object
      description: Utilisateur dans Jira
      properties:
        name:
          type: string
        emailAddress:
          type: string
        displayName:
          type: string
        avatarUrls:
          $ref: '#/components/schemas/Avatars'
      x-examples:
        Gérald:
          name: U00I348
          emailAddress: gberjot@agirc-arrco.fr
          displayName: Gérald BERJOT
          avatarUrls:
            16x16: 'https://jira-h.retraite.aa/secure/useravatar?size=xsmall&ownerId=u00i348&avatarId=13450'
            24x24: 'https://jira-h.retraite.aa/secure/useravatar?size=small&ownerId=u00i348&avatarId=13450'
            32x32: 'https://jira-h.retraite.aa/secure/useravatar?size=medium&ownerId=u00i348&avatarId=13450'
            48x48: 'https://jira-h.retraite.aa/secure/useravatar?ownerId=u00i348&avatarId=13450'
        Hugo:
          name: U00I701
          emailAddress: hlouvet@agirc-arrco.fr
          displayName: Hugo LOUVET
          avatarUrls:
            16x16: 'https://jira-h.retraite.aa/secure/useravatar?size=xsmall&ownerId=u00i701&avatarId=22601'
            24x24: 'https://jira-h.retraite.aa/secure/useravatar?size=small&ownerId=u00i701&avatarId=22601'
            32x32: 'https://jira-h.retraite.aa/secure/useravatar?size=medium&ownerId=u00i701&avatarId=22601'
            48x48: 'https://jira-h.retraite.aa/secure/useravatar?ownerId=u00i701&avatarId=22601'
    Avatars:
      title: Avatars
      type: object
      properties:
        16x16:
          type: string
        24x24:
          type: string
        32x32:
          type: string
        48x48:
          type: string
      x-examples:
        Tania:
          16x16: 'https://jira-h.retraite.aa/secure/useravatar?size=xsmall&ownerId=u00i178&avatarId=11818'
          24x24: 'https://jira-h.retraite.aa/secure/useravatar?size=small&ownerId=u00i178&avatarId=11818'
          32x32: 'https://jira-h.retraite.aa/secure/useravatar?size=medium&ownerId=u00i178&avatarId=11818'
          48x48: 'https://jira-h.retraite.aa/secure/useravatar?ownerId=u00i178&avatarId=11818'
        Olivier M:
          16x16: 'https://jira-h.retraite.aa/secure/useravatar?size=xsmall&ownerId=u00i100&avatarId=13461'
          24x24: 'https://jira-h.retraite.aa/secure/useravatar?size=small&ownerId=u00i100&avatarId=13461'
          32x32: 'https://jira-h.retraite.aa/secure/useravatar?size=medium&ownerId=u00i100&avatarId=13461'
          48x48: 'https://jira-h.retraite.aa/secure/useravatar?ownerId=u00i100&avatarId=13461'
      description: URLs des images des avatars d'un utilisateur JIRA
  securitySchemes:
    Basic Auth:
      type: http
      scheme: basic
